export const metadata = {
  title: 'Home - Portifólio Kauã Lusvarghi',
  // description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
